# These are supported funding model platforms
We prefer crypto because, well, we're nerds. 
This is a one-man project so every penny helps support the growth of this project and payment of it's servers! 

Thank you very much!

github: nolyoi
ko_fi: nolyoiy

